"""add product_aliases table

Revision ID: 7aadc53c1d48
Revises: 9b1c3d5e7f8a
Create Date: 2026-05-23 20:09:20.258169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aadc53c1d48'
down_revision = '9b1c3d5e7f8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_aliases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alias_source', sa.String(length=50), nullable=False),
    sa.Column('alias_id', sa.String(length=100), nullable=False),
    sa.Column('canonical_product_id', sa.UUID(), nullable=False),
    sa.Column('match_type', sa.Enum('BARCODE', 'FUZZY', 'MANUAL', name='matchtype'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['canonical_product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias_source', 'alias_id', name='uq_alias_source_id')
    )
    op.create_index(op.f('ix_product_aliases_alias_id'), 'product_aliases', ['alias_id'], unique=False)
    op.create_index(op.f('ix_product_aliases_alias_source'), 'product_aliases', ['alias_source'], unique=False)
    op.create_index(op.f('ix_price_history_province'), 'price_history', ['province'], unique=False)
    op.create_index(op.f('ix_price_history_region'), 'price_history', ['region'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_history_region'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_province'), table_name='price_history')
    op.drop_index(op.f('ix_product_aliases_alias_source'), table_name='product_aliases')
    op.drop_index(op.f('ix_product_aliases_alias_id'), table_name='product_aliases')
    op.drop_table('product_aliases')
    # ### end Alembic commands ###
