"""initial_tables

Revision ID: fb80705162b3
Revises: 
Create Date: 2026-03-18 16:55:30.988178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb80705162b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('economic_indicators',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('indicator_type', sa.Enum('INFLATION_MONTHLY', 'INFLATION_YEARLY', 'DOLLAR_BLUE', 'DOLLAR_OFICIAL', 'DOLLAR_MEP', 'DOLLAR_CCL', 'UVA_INDEX', 'PLAZO_FIJO_RATE', 'RISK_COUNTRY', 'IPC_CATEGORY', name='indicatortype'), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('source', sa.Enum('ARGENTINADATOS', 'DATOS_GOB_AR', 'BCRA', 'INDEC', name='datasource'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_indicator_category_date', 'economic_indicators', ['indicator_type', 'category', 'date'], unique=False)
    op.create_index('idx_indicator_date', 'economic_indicators', ['indicator_type', 'date'], unique=False)
    op.create_index(op.f('ix_economic_indicators_date'), 'economic_indicators', ['date'], unique=False)
    op.create_index(op.f('ix_economic_indicators_indicator_type'), 'economic_indicators', ['indicator_type'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('category', sa.Enum('ALIMENTOS', 'BEBIDAS', 'LIMPIEZA', 'HIGIENE_PERSONAL', 'LACTEOS', 'CARNES', 'FRUTAS_VERDURAS', 'PANADERIA', 'CONGELADOS', 'SNACKS', 'DESAYUNO', 'OTROS', name='productcategory'), nullable=False),
    sa.Column('unit', sa.Enum('KG', 'G', 'L', 'ML', 'UNIDAD', 'PACK', name='productunit'), nullable=False),
    sa.Column('quantity', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=True)
    op.create_index(op.f('ix_products_brand'), 'products', ['brand'], unique=False)
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_normalized_name'), 'products', ['normalized_name'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('supermarket', sa.Enum('CARREFOUR', 'COTO', 'DISCO', name='supermarket'), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('was_on_sale', sa.Boolean(), nullable=True),
    sa.Column('original_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('in_stock', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_supermarket_date', 'price_history', ['product_id', 'supermarket', 'scraped_at'], unique=False)
    op.create_index('idx_supermarket_date', 'price_history', ['supermarket', 'scraped_at'], unique=False)
    op.create_index(op.f('ix_price_history_scraped_at'), 'price_history', ['scraped_at'], unique=False)
    op.create_index(op.f('ix_price_history_supermarket'), 'price_history', ['supermarket'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_history_supermarket'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_scraped_at'), table_name='price_history')
    op.drop_index('idx_supermarket_date', table_name='price_history')
    op.drop_index('idx_product_supermarket_date', table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_products_normalized_name'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_index(op.f('ix_products_brand'), table_name='products')
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_economic_indicators_indicator_type'), table_name='economic_indicators')
    op.drop_index(op.f('ix_economic_indicators_date'), table_name='economic_indicators')
    op.drop_index('idx_indicator_date', table_name='economic_indicators')
    op.drop_index('idx_indicator_category_date', table_name='economic_indicators')
    op.drop_table('economic_indicators')
    # ### end Alembic commands ###
